### main  page
GET http://localhost:3000/

### get all products
GET http://localhost:3000/api/products

### get single product by id
GET http://localhost:3000/api/products/2

### get all categories
GET http://localhost:3000/api/categories

### get products by category ID
GET http://localhost:3000/api/products/category/1

### sort products by date desc
GET http://localhost:3000/api/sort/date

### Create product
POST http://localhost:3000/api/products
Content-Type:  application/json

{
    "title": "MacBook Pro M2",
    "username": "skirma",
    "date": "2024-01-12",
    "content": "new laptop",
    "cat_id": "3",
    "price": 3000,
    "p_condition": "new"
  
}

### Delete ad by ID
DELETE  http://localhost:3000/api/products/28

### Edit Product
PUT http://localhost:3000/api/products/2
Content-Type:  application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InRlc3RAdGVzdDIubHQiLCJzdWIiOjE1LCJpYXQiOjE3MDU1MTUxNTEsImV4cCI6MTcwNTUxODc1MX0.JxB-4M8zAp9XHATbTDdccS0Kwb2m0UAJ-UuGifSGdUw


{
    "title": "Edited Product2",
    "content": "Edited content",
    "cat_id": 2,
    "price": 3333,
    "p_condition": "new"
}

### Search products by string
GET http://localhost:3000/api/search/gpu

### Search products by owner
GET http://localhost:3000/api/owner/skirma


### REGISTER User 
POST http://localhost:3000/api/auth/register 
Content-Type: application/json

{
"username": "test1", 
"email": "test1@secure.com", 
"password": "123456"
}

### LOGIN User 
POST http://localhost:3000/api/auth/login
Content-Type: application/json

{
"email": "test@test2.lt", 
"password": "123456"
}

### get all product comments
GET http://localhost:3000/api/comments/product/1

### create comment for product with ID
POST http://localhost:3000/api/comments/product/1
Content-Type:  application/json

{
  "comm_author": "skirma",
  "comm_context": "Labai informatyvu, labai....",
  "comm_date": "2024-12-24"
}

### DELETE comment by ID
DELETE  http://localhost:3000/api/comments/2