### main  page
GET http://localhost:3000/

### get all products
GET http://localhost:3000/api/products

### get single product by id
GET http://localhost:3000/api/products/1

### get all categories
GET http://localhost:3000/api/categories

### get products by category ID
GET http://localhost:3000/api/products/category/4

### Create product
POST http://localhost:3000/api/products
Content-Type:  application/json

{
    "title": "MacBook Pro M2",
    "username": "skirma",
    "date": "2024-01-12",
    "content": "new laptop",
    "cat_id": "3",
    "price": 3000,
    "p_condition": "new"
  
}

### Delete ad by ID
DELETE  http://localhost:3000/api/products/11

### Edit AD
PUT http://localhost:3000/api/products/12
Content-Type:  application/json

{
    "title": "Edited Post 1",
    "author": "Author 1",
    "date": "2022-07-07",
    "content": "Test content",
    "cat_id": 1001,
    "price": 201,
    "sub_id": 4001
}

### Search products
GET http://localhost:3000/api/search/gpu


### REGISTER User 
POST http://localhost:3000/api/auth/register 
Content-Type: application/json

{
"username": "test1", 
"email": "test1@secure.com", 
"password": "123456"
}

### LOGIN User 
POST http://localhost:3000/api/auth/login
Content-Type: application/json

{
"email": "test1@secure.lt", 
"password": "123456"
}