### main  page
GET http://localhost:3000/

### get all ads 
GET http://localhost:3000/api/ads

### Create ad
POST http://localhost:3000/api/ads
Content-Type:  application/json

{
    "title": "Post 1",
    "author": "Author 1",
    "date": "2022-07-07",
    "content": "Text Area of text",
    "cat_id": 1
}

### Delete ad by ID
DELETE  http://localhost:3000/api/ads/1

### Edit AD
PUT http://localhost:3000/api/ads/2
Content-Type:  application/json

{
    "title": "Edited Post1",
    "author": "Edited Auth",
    "date": "2011-11-11",
    "content": "Text Area of text",
    "cat_id": 3
}